# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
Application : General - Setting programs and human services - Industry and factories - Robotics and technology - Collective management - New and accurate algorithm for all activities and jobs
Benefits: Adjust body biological clock - Achieve the highest level of brain function - Increase longevity - Accurate and varied division - See the passage of time - The day is divided into 4 seasons of 10 parts - Accurate calculation of the earth's rotation around itself and around the sun, including leaps and bounds - Accurate and better division for days of the week and month - A launching pad for building a better earth and tomorrow - Leaving  routine and monotonous life - A gateway to enter science, consciousness, perception, intelligent mind and ...) A gift to humanity (
